notifications:
  email:
    false

dist: trusty
sudo: false

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "nightly"

before_script:
  - sudo apt-get install -qq openjdk-7-jre

script:
  - python setup.py test


deploy:
  provider: pypi
  user: moxfyre
  password:
    secure: VFWdA/2c9Vtf1oB3xa51X6ZpJAxBXTEwEF5mwEcPdlbuT5GzfrZT4gETkFzZRj3HWk+a7MRhBK5YHhlosBFC1tYMB0MkrI2/aYDoLEzCcpCJHBAvmG4+ycqcJaCBqbOhtWyXQwRNg7b2Eso29V0FtCWj6MdhALC23MCo1MFGDJz5uWsAliE8Qzynby9MB2ek471SR0xWGH/HfnqFmt8Pum7Mq/MBs8HYhE2irVOrvgLyCQfII2LMA/ns0zUsh2S/usfFrnxjSWRnd3EqUbV5BCzWmNWB6KylqRqedzLHvcgHgxedggH7Mviim4mXoDSwElt5P7rzMG/jBCNIhR2fExxNKc7kk+wrFFGxaoWCANAZsbY8sQEcRSVWqpiFh3y9LnBr2ZRXrPjpO4GpLP0494Y0AHXVURxud9SABiVXwXxwDpw7hc/fCb6PEEIhO4J7cZ0GIX8cSBz30+NxiTfbRrGAENRjcdSjoV/VFLRLKfeT96HbVae/jQJpLIa/qnn0qexqJhCGkOIcbR6rvqSZaFAPFT2iqHDAVv9M7IFS/ecL8is2s2qUaPfI8LCxUTLXeMZ/woI2cix+x60Nt1EM+Yg3CnICO4pM0EaTe3tc+lFkLhJ8z3Aa05/0XZ3sqsbzVJKDua10ye/fGxJUdjW/jWYZ+hzNy22CBq2RSy/3UE8=
  on:
    tags: true
    repo: dlenski/python-zxing
